# This is a basic workflow to help you get started with Actions

name: 3 - Post Standup Notes

# Controls when the workflow will run
on:
  schedule:
    - cron:  '20 20 * * 1-5' #'0 4 * * 1-5' # Runs M-F at 4:00am UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Remind channel to turn in standup notes
        run: |
          curl -s -X POST "${{ secrets.WEBHOOK_URL }}" -d "content=Turn in standup notes."
